### ISSUE TITLE
Arithmetic operation resulted in an overflow.

### ISSUE THREAD

**Issue by mikkelam** [inlinevoid/HLDJConverter#1]
Hey there i am trying to process an mp3 which works fine, what happens is the second i start the converting i get this error:

System.OverflowException: Arithmetic operation resulted in an overflow.
      at HLDJConverter.MediaConverter.<FixFFmpegWavFileHeader>d__3.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at HLDJConverter.MediaConverter.<>c__DisplayClass0_0.<<FFmpegConvertToWavAsync>b__1>d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at HLDJConverter.MediaConverter.<>c__DisplayClass0_0.<<FFmpegConvertToWavAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__5(Object state)
      at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
      at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
      at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
      at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
      at System.Threading.ThreadPoolWorkQueue.Dispatch()
      at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by PowerOfDark** [comment]
Fixed. Pull request is on the way.
